import os
import pandas as pd
from PyPDF2 import PdfReader
from pptx import Presentation
from pptx.util import Inches
import webbrowser
import shlex
import subprocess

class ProductivityTools:
    @staticmethod
    def summarize_pdf(filepath: str) -> str:
        """Extracts text from a PDF for summarization."""
        if not os.path.exists(filepath):
            return f"I'm sorry Sir, I couldn't find the file at {filepath}."
        try:
            reader = PdfReader(filepath)
            text = ""
            for page in reader.pages[:5]: # Limit to first 5 pages for brevity
                text += page.extract_text()
            return f"Extracted content from {os.path.basename(filepath)}: {text[:2000]}..."
        except Exception as e:
            return f"Error reading PDF: {str(e)}"

    @staticmethod
    def analyze_excel(filepath: str) -> str:
        """Reads an Excel file and returns basic stats."""
        if not os.path.exists(filepath):
            return f"File {filepath} not found, Sir."
        try:
            df = pd.read_excel(filepath)
            summary = df.describe().to_string()
            return f"Analysis of {os.path.basename(filepath)} completed. Here are the statistics:\n{summary}"
        except Exception as e:
            return f"Error analyzing Excel: {str(e)}"

    @staticmethod
    def create_powerpoint(topic: str, content: str) -> str:
        """Creates a simple PowerPoint presentation."""
        try:
            prs = Presentation()
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title = slide.shapes.title
            subtitle = slide.placeholders[1]

            title.text = topic
            subtitle.text = "Generated by JARVIS"

            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]

            title_shape.text = "Key Points"
            tf = body_shape.text_frame
            tf.text = content

            filename = f"assets/{topic.replace(' ', '_')}.pptx"
            os.makedirs("assets", exist_ok=True)
            prs.save(filename)
            return f"Presentation created successfully: {filename}, Sir."
        except Exception as e:
            return f"Failed to create PowerPoint: {str(e)}"

    @staticmethod
    def draft_email(recipient: str, subject: str, body: str) -> str:
        """Drafts an email by opening the mailto link."""
        try:
            url = f"mailto:{recipient}?subject={subject}&body={body}"
            webbrowser.open(url)
            return f"I've prepared the email to {recipient} for you, Sir."
        except Exception as e:
            return f"Failed to draft email: {str(e)}"

productivity_tools_list = [
    ProductivityTools.summarize_pdf,
    ProductivityTools.analyze_excel,
    ProductivityTools.create_powerpoint,
    ProductivityTools.draft_email
]
